
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 17 04:51:40 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALSTO = 27;
  public static final int PLUSPLUS = 36;
  public static final int CONST = 6;
  public static final int LPAREN = 40;
  public static final int GREATER = 29;
  public static final int SEMI = 5;
  public static final int CONTINUE = 21;
  public static final int LESS = 31;
  public static final int MINUS = 23;
  public static final int RPAREN = 41;
  public static final int AND = 33;
  public static final int OR = 34;
  public static final int COMMA = 38;
  public static final int BOOL = 10;
  public static final int ELESS = 32;
  public static final int DOUBLEDOT = 44;
  public static final int DIV = 25;
  public static final int DIFFERENT = 28;
  public static final int PLUS = 22;
  public static final int IF = 16;
  public static final int LSQBRACE = 42;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 37;
  public static final int RETURN = 12;
  public static final int EQUAL = 35;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int NUMBER = 8;
  public static final int EGREATER = 30;
  public static final int MOD = 26;
  public static final int BREAK = 14;
  public static final int IDENT = 7;
  public static final int VOID = 13;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int READ = 20;
  public static final int GOTO = 45;
  public static final int CHARCONST = 9;
  public static final int WHILE = 18;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int RSQBRACE = 43;
  public static final int PRINT = 11;
  public static final int DO = 17;
}

